version: '3'

services:
    mysql:
        container_name: pfa-mysql
        image: mysql:8.0
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_PASSWORD=""
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        networks:
            - backend

    go:
        container_name: pfa_go
        image: roodrigolr/desafio-docker1-pfa
        environment:
            - MYSQL_URL=mysql
            - MYSQL_DBNAME=desafio_docker
            - API_PORT=3000
            - MYSQL_USER=root
        networks:
            - backend
            - frontend
        depends_on:
            - mysql

    nginx:
        container_name: pfa-nginx
        build: ./nginx-compose
        ports:
            - 8000:80
        networks:
            - frontend
        depends_on:
            - go

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge

